### ISSUE TITLE
Configurable Start-Day of the Week

### ISSUE THREAD

**Issue by JBHoren** [dmedvinsky/gsimplecal#44]
If I was still back home, it would be nice that the weeks began on Sunday; but I'm not there... I'm here, in the US, where the week begins on Monday. So, would it be too much trouble to make the Start-Day of the Week user-configurable?

**Comment by dmedvinsky** [comment]
It is user-configurable already. It's even documented in the manpage. You change the first day of the week by changing your system locale. Because first day of the week, as you have noticed, depends on your locality. If you don't want to change your locale system-wide, there is a config option in gsimplecal named `force_lang`. It will only apply to gsimplecal process, thus changing the first day of the week for gsimplecal without affecting your system locale.

Please refer to manpage for more info if required.

**Comment by JBHoren** [comment]
As a former technical writer, I did RTFM. But what? I needed to use `force_lang=en_GB.UTF8` for a week that begins on Monday, but did not have that locale installed, so adding the line to the config file did nothing. Fixed that. Thanks!

**Comment by dmedvinsky** [comment]
Yeah, the manpage mentions that the option must take a value that's one of the `locale -a` output. I guess the author (me, probably) assumed the knowledge of what that is and how that works.

If you can suggest a concise description to amend that incompleteness, I'd gladly amend the doc.

**Comment by JBHoren** [comment]
Yes, forcibly setting `LANG=en_GB.UTF8 `in the config file works. My objection was that I'm a US English snob; but what I found _really_ objectionable was that the `en_US` locale has the week starting on Sunday! In the end, I chose to go with a more granular solution, in the form of `exec:LC_TIME=en_GB.UTF8 gsimplecal` in my window manager (JWM) panel. Works fine. Sorry for the inconvenience. It's a wonderful program, and I appreciate your sharing it with us.
